export const ADD_FILES = "ADD_FILES";
export const UPDATE_FILE_UPLOAD_PROGRESS = "UPDATE_FILE_UPLOAD_PROGRESS";
export const DELETE_FILE = "DELETE_FILE";
export const INIT_APP_STARTED = "INIT_APP_STARTED";
export const INIT_APP_FINISHED = "INIT_APP_FINISHED";
export const INIT_APP_FAILED = "INIT_APP_FAILED";